# Generated by Django 4.1.7 on 2023-07-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_remove_blooddonate_age_alter_blooddonate_disease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='age',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='other', max_length=8),
        ),
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
