# Generated by Django 4.1.7 on 2023-03-05 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood', '0002_alter_bloodrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='patient_age',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='request_by_donor',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='request_by_patient',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='request_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
