# Generated by Django 4.1.7 on 2023-07-12 12:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_remove_blooddonate_age_alter_blooddonate_disease_and_more'),
        ('blood', '0003_remove_bloodrequest_patient_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonateTest',
            fields=[
                ('test_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('application_id', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('blood_group', models.CharField(max_length=5)),
                ('pint_amount', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('failed', 'failed'), ('approved', 'approved')], max_length=15)),
                ('reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.donor')),
            ],
        ),
    ]
