# Generated by Django 4.1.7 on 2023-07-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_blooddonatetest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonatetest',
            name='date',
        ),
        migrations.AddField(
            model_name='blooddonatetest',
            name='request_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blooddonatetest',
            name='test_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blooddonatetest',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='blooddonatetest',
            name='pint_amount',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='blooddonatetest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('failed', 'failed'), ('approved', 'approved')], default='pending', max_length=15),
        ),
    ]
