# Generated by Django 4.1.7 on 2023-07-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_remove_blooddonatetest_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonatetest',
            name='pint_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
